# Generated by Django 4.2.2 on 2023-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ManyToManyField(blank=True, to='learning_app.product'),
        ),
    ]
