# Generated by Django 4.2.2 on 2023-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_alter_lesson_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='product',
            field=models.ManyToManyField(to='learning_app.product'),
        ),
    ]
