# Generated by Django 4.2.2 on 2023-09-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_alter_userlessoninfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessoninfo',
            name='last_time_watched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
