# Generated by Django 4.2.2 on 2023-09-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0006_userlessoninfo_last_time_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_app.product'),
        ),
    ]
