# Generated by Django 4.2.2 on 2023-09-21 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_app', '0008_alter_userproducts_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproducts',
            unique_together={('user', 'product')},
        ),
    ]
