# Generated by Django 4.2.2 on 2023-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0009_alter_userproducts_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessoninfo',
            name='status',
            field=models.CharField(choices=[('YES', 'Watched'), ('NO', 'Not watched')], default=False, max_length=12),
        ),
    ]
