# Generated by Django 4.2.2 on 2023-09-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0010_userlessoninfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessoninfo',
            name='status',
            field=models.CharField(blank=True, choices=[('YES', 'Watched'), ('NO', 'Not watched')], max_length=12),
        ),
    ]
